cabal-version:      3.0
name:               tile
version:            0.1.0.0
-- synopsis:
-- description:
license:            BSD-3-Clause
license-file:       LICENSE
author:             Shane Fletcher
maintainer:         shayne@shaynefletcher.org
-- copyright:
category:           System
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

common warnings
    ghc-options: -Wall

library
    import:           warnings

    exposed-modules:
      Tile
      Tile.Shape
      Tile.Range
      Tile.Tile
      Tile.Tiling
      Tile.Schedule
      Tile.Execution
      Tile.Layout
      Tile.Neighborhood
      Tile.Geometry

    -- other-modules:
    -- other-extensions:

    build-depends:    base ^>=4.22.0.0
                    , containers
    hs-source-dirs:   src
    default-language: GHC2024

executable tile-demo
  main-is: Main.hs
  hs-source-dirs: app
  build-depends:
      base >=4.18 && <4.23,
      tile
  default-language: GHC2024

test-suite tile-test
    import:           warnings
    default-language: GHC2024
    -- other-modules:
    -- other-extensions:
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs
    build-depends:
        base ^>=4.22.0.0,
        tile,
        tasty >=1.4,
        tasty-hunit >=0.10
